// types/note.ts
import * as z from "zod"; // <-- Import zod here if you haven't already

export const noteSchema = z.object({
  title: z.string().min(1, "Title is required"),
  content: z.string().min(1, "Content is required"),
  tag: z.enum([
    "Todo",
    "Work",
    "Personal",
    "Meeting",
    "Shopping",
    "Ideas",
    "Travel",
    "Finance",
    "Health",
    "Important",
  ] as const),
});

// Derive NoteData directly from the Zod schema
export type NoteData = z.infer<typeof noteSchema>;

// Your existing Tag type (can remain as is or be derived too if you prefer)
export const tags = [
  "Todo",
  "Work",
  "Personal",
  "Meeting",
  "Shopping",
  "Ideas",
  "Travel",
  "Finance",
  "Health",
  "Important",
] as const;

export type Tag = (typeof tags)[number];

// If you have other Note related types:
export interface Note {
  _id: string; // Assuming an ID generated by your backend
  title: string;
  content: string;
  tag: Tag; // Use the Tag type
  owner: string; // Assuming a user ID
  createdAt: string;
  updatedAt: string;
}

export interface PaginatedNotesResponse {
  notes: Note[];
  totalPages: number;
  currentPage: number;
  totalNotes: number;
}

// A helper function to validate if a string is a valid Tag or "All"
export function isTagOrAll(value: string): value is Tag | "All" {
  return tags.includes(value as Tag) || value === "All";
}
